/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The application type. The value of this property affects the validation steps for a redirect
  * URI. See the description about `redirectUris` property for more details.
  */
enum ApplicationType(val value: String) derives ConfiguredJsonValueCodec {

  case WEB      extends ApplicationType("WEB")
  case `NATIVE` extends ApplicationType("NATIVE")

}

object ApplicationType {

  def withValueOpt(value: String): Option[ApplicationType] = ApplicationType
    .values
    .find(_.value == value)

  def withValue(value: String): ApplicationType =
    withValueOpt(value).getOrElse(
      throw java.lang.IllegalArgumentException(s"ApplicationType enum case not found: $value")
    )

  given decoderApplicationType: Decoder[ApplicationType] = Decoder.decodeString.map(withValue)

  given encoderApplicationType: Encoder[ApplicationType] = Encoder
    .encodeString
    .contramap[ApplicationType](_.value)

}
