/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import scala.collection.immutable.Seq

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*
import org.checkerframework.checker.units.qual.g

/**
  * The authorization details. This represents the value of the `authorization_details` request
  * parameter in the preceding device authorization request which is defined in \"OAuth 2.0 Rich
  * Authorization Requests\".
  * @param elements
  *   Elements of this authorization details.
  */
case class AuthzDetails(
    elements: Option[Seq[AuthorizationDetailsElement]] = None
)

object AuthzDetails {

  given jsonCodec: JsonValueCodec[AuthzDetails] = JsonCodecMaker.make(codecMakerConfig)

  given encoderAuthzDetails: Encoder[AuthzDetails] = Encoder.instance { t =>
    Json.fromFields {
      Seq(
        t.elements.map(v => "elements" -> v.asJson)
      ).flatten
    }
  }

  given decoderAuthzDetails: Decoder[AuthzDetails] = Decoder.instance { c =>
    for {
      elements <- c.downField("elements").as[Option[Seq[AuthorizationDetailsElement]]]
    } yield AuthzDetails(
      elements = elements
    )
  }

}
