/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

sealed trait Authorization

object Authorization {

  final case class Basic(username: String, password: Option[String] = None) extends Authorization
  final case class ApiKey(name: String, value: String)                      extends Authorization
  final case class Bearer(token: String)                                    extends Authorization

}
