/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum AuthorizationResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends AuthorizationResponseAction("INTERNAL_SERVER_ERROR")
  case BADREQUEST          extends AuthorizationResponseAction("BAD_REQUEST")
  case LOCATION            extends AuthorizationResponseAction("LOCATION")
  case FORM                extends AuthorizationResponseAction("FORM")
  case NOINTERACTION       extends AuthorizationResponseAction("NO_INTERACTION")
  case INTERACTION         extends AuthorizationResponseAction("INTERACTION")

}

object AuthorizationResponseAction {

  def withValueOpt(value: String): Option[AuthorizationResponseAction] = AuthorizationResponseAction
    .values
    .find(_.value == value)

  def withValue(value: String): AuthorizationResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"AuthorizationResponseAction enum case not found: $value")
    )

  given decoderAuthorizationResponseAction: Decoder[AuthorizationResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderAuthorizationResponseAction: Encoder[AuthorizationResponseAction] = Encoder
    .encodeString
    .contramap[AuthorizationResponseAction](_.value)

}
