/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum AuthorizationFailResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends AuthorizationFailResponseAction("INTERNAL_SERVER_ERROR")
  case BADREQUEST          extends AuthorizationFailResponseAction("BAD_REQUEST")
  case LOCATION            extends AuthorizationFailResponseAction("LOCATION")
  case FORM                extends AuthorizationFailResponseAction("FORM")

}

object AuthorizationFailResponseAction {

  def withValueOpt(value: String): Option[AuthorizationFailResponseAction] =
    AuthorizationFailResponseAction.values.find(_.value == value)

  def withValue(value: String): AuthorizationFailResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"AuthorizationFailResponseAction enum case not found: $value")
    )

  given decoderAuthorizationFailResponseAction: Decoder[AuthorizationFailResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderAuthorizationFailResponseAction: Encoder[AuthorizationFailResponseAction] = Encoder
    .encodeString
    .contramap[AuthorizationFailResponseAction](_.value)

}
