/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum BackchannelAuthenticationFailResponseAction(val value: String)
    derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR
      extends BackchannelAuthenticationFailResponseAction("INTERNAL_SERVER_ERROR")

  case BADREQUEST extends BackchannelAuthenticationFailResponseAction("BAD_REQUEST")
  case FORBIDDEN  extends BackchannelAuthenticationFailResponseAction("FORBIDDEN")

}

object BackchannelAuthenticationFailResponseAction {

  def withValueOpt(value: String): Option[BackchannelAuthenticationFailResponseAction] =
    BackchannelAuthenticationFailResponseAction.values.find(_.value == value)

  def withValue(value: String): BackchannelAuthenticationFailResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(
          s"BackchannelAuthenticationFailResponseAction enum case not found: $value"
        )
    )

  given decoderBackchannelAuthenticationFailResponseAction
      : Decoder[BackchannelAuthenticationFailResponseAction] = Decoder.decodeString.map(withValue)

  given encoderBackchannelAuthenticationFailResponseAction
      : Encoder[BackchannelAuthenticationFailResponseAction] = Encoder
    .encodeString
    .contramap[BackchannelAuthenticationFailResponseAction](_.value)

}
