/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum BackchannelAuthenticationIssueResponseAction(val value: String)
    derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR
      extends BackchannelAuthenticationIssueResponseAction("INTERNAL_SERVER_ERROR")

  case INVALIDTICKET extends BackchannelAuthenticationIssueResponseAction("INVALID_TICKET")
  case OK            extends BackchannelAuthenticationIssueResponseAction("OK")

}

object BackchannelAuthenticationIssueResponseAction {

  def withValueOpt(value: String): Option[BackchannelAuthenticationIssueResponseAction] =
    BackchannelAuthenticationIssueResponseAction.values.find(_.value == value)

  def withValue(value: String): BackchannelAuthenticationIssueResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(
          s"BackchannelAuthenticationIssueResponseAction enum case not found: $value"
        )
    )

  given decoderBackchannelAuthenticationIssueResponseAction
      : Decoder[BackchannelAuthenticationIssueResponseAction] = Decoder.decodeString.map(withValue)

  given encoderBackchannelAuthenticationIssueResponseAction
      : Encoder[BackchannelAuthenticationIssueResponseAction] = Encoder
    .encodeString
    .contramap[BackchannelAuthenticationIssueResponseAction](_.value)

}
