/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The result of the end-user authentication and authorization. One of the following. Details are
  * described in the description.
  */
enum BackchannelAuthenticationCompleteRequestResult(val value: String)
    derives ConfiguredJsonValueCodec {

  case TRANSACTIONFAILED
      extends BackchannelAuthenticationCompleteRequestResult("TRANSACTION_FAILED")

  case ACCESSDENIED extends BackchannelAuthenticationCompleteRequestResult("ACCESS_DENIED")
  case AUTHORIZED   extends BackchannelAuthenticationCompleteRequestResult("AUTHORIZED")

}

object BackchannelAuthenticationCompleteRequestResult {

  def withValueOpt(value: String): Option[BackchannelAuthenticationCompleteRequestResult] =
    BackchannelAuthenticationCompleteRequestResult.values.find(_.value == value)

  def withValue(value: String): BackchannelAuthenticationCompleteRequestResult =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(
          s"BackchannelAuthenticationCompleteRequestResult enum case not found: $value"
        )
    )

  given decoderBackchannelAuthenticationCompleteRequestResult
      : Decoder[BackchannelAuthenticationCompleteRequestResult] = Decoder
    .decodeString
    .map(withValue)

  given encoderBackchannelAuthenticationCompleteRequestResult
      : Encoder[BackchannelAuthenticationCompleteRequestResult] = Encoder
    .encodeString
    .contramap[BackchannelAuthenticationCompleteRequestResult](_.value)

}
