/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum BackchannelAuthenticationResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends BackchannelAuthenticationResponseAction("INTERNAL_SERVER_ERROR")
  case BADREQUEST          extends BackchannelAuthenticationResponseAction("BAD_REQUEST")
  case UNAUTHORIZED        extends BackchannelAuthenticationResponseAction("UNAUTHORIZED")
  case USERIDENTIFICATION  extends BackchannelAuthenticationResponseAction("USER_IDENTIFICATION")

}

object BackchannelAuthenticationResponseAction {

  def withValueOpt(value: String): Option[BackchannelAuthenticationResponseAction] =
    BackchannelAuthenticationResponseAction.values.find(_.value == value)

  def withValue(value: String): BackchannelAuthenticationResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(
          s"BackchannelAuthenticationResponseAction enum case not found: $value"
        )
    )

  given decoderBackchannelAuthenticationResponseAction
      : Decoder[BackchannelAuthenticationResponseAction] = Decoder.decodeString.map(withValue)

  given encoderBackchannelAuthenticationResponseAction
      : Encoder[BackchannelAuthenticationResponseAction] = Encoder
    .encodeString
    .contramap[BackchannelAuthenticationResponseAction](_.value)

}
