/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * @param resultCode
  *   The code which represents the result of the API call.
  * @param resultMessage
  *   A short message which explains the result of the API call.
  * @param action
  * @param responseContent
  *   The content that the authorization server implementation is to return to the client
  *   application. Its format varies depending on the value of `action` parameter.
  * @param authReqId
  *   The newly issued authentication request ID.
  * @param expiresIn
  *   The duration of the issued authentication request ID in seconds.
  * @param interval
  *   The minimum amount of time in seconds that the client must wait for between polling requests
  *   to the token endpoint.
  */
case class BackchannelAuthenticationIssueResponse(
    resultCode: Option[String] = None,
    resultMessage: Option[String] = None,
    action: Option[BackchannelAuthenticationIssueResponseAction] = None,
    responseContent: Option[String] = None,
    authReqId: Option[String] = None,
    expiresIn: Option[Int] = None,
    interval: Option[Int] = None
)

object BackchannelAuthenticationIssueResponse {

  given jsonCodec: JsonValueCodec[BackchannelAuthenticationIssueResponse] =
    JsonCodecMaker.make(codecMakerConfig)

  given encoderBackchannelAuthenticationIssueResponse
      : Encoder[BackchannelAuthenticationIssueResponse] = Encoder.instance { t =>
    Json.fromFields {
      Seq(
        t.resultCode.map(v => "resultCode" -> v.asJson),
        t.resultMessage.map(v => "resultMessage" -> v.asJson),
        t.action.map(v => "action" -> v.asJson),
        t.responseContent.map(v => "responseContent" -> v.asJson),
        t.authReqId.map(v => "authReqId" -> v.asJson),
        t.expiresIn.map(v => "expiresIn" -> v.asJson),
        t.interval.map(v => "interval" -> v.asJson)
      ).flatten
    }
  }

  given decoderBackchannelAuthenticationIssueResponse
      : Decoder[BackchannelAuthenticationIssueResponse] = Decoder.instance { c =>
    for {
      resultCode    <- c.downField("resultCode").as[Option[String]]
      resultMessage <- c.downField("resultMessage").as[Option[String]]
      action <- mapEmptyStringToNull(c.downField("action")).as[Option[
                  BackchannelAuthenticationIssueResponseAction
                ]]
      responseContent <- c.downField("responseContent").as[Option[String]]
      authReqId       <- c.downField("authReqId").as[Option[String]]
      expiresIn       <- c.downField("expiresIn").as[Option[Int]]
      interval        <- c.downField("interval").as[Option[Int]]
    } yield BackchannelAuthenticationIssueResponse(
      resultCode = resultCode,
      resultMessage = resultMessage,
      action = action,
      responseContent = responseContent,
      authReqId = authReqId,
      expiresIn = expiresIn,
      interval = interval
    )
  }

}
