/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum BackchannelAuthenticationCompleteResponseAction(val value: String)
    derives ConfiguredJsonValueCodec {

  case SERVERERROR  extends BackchannelAuthenticationCompleteResponseAction("SERVER_ERROR")
  case NOACTION     extends BackchannelAuthenticationCompleteResponseAction("NO_ACTION")
  case NOTIFICATION extends BackchannelAuthenticationCompleteResponseAction("NOTIFICATION")

}

object BackchannelAuthenticationCompleteResponseAction {

  def withValueOpt(value: String): Option[BackchannelAuthenticationCompleteResponseAction] =
    BackchannelAuthenticationCompleteResponseAction.values.find(_.value == value)

  def withValue(value: String): BackchannelAuthenticationCompleteResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(
          s"BackchannelAuthenticationCompleteResponseAction enum case not found: $value"
        )
    )

  given decoderBackchannelAuthenticationCompleteResponseAction
      : Decoder[BackchannelAuthenticationCompleteResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderBackchannelAuthenticationCompleteResponseAction
      : Encoder[BackchannelAuthenticationCompleteResponseAction] = Encoder
    .encodeString
    .contramap[BackchannelAuthenticationCompleteResponseAction](_.value)

}
