/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import scala.collection.immutable.Seq

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * @param requestableScopes
  *   The set of scopes that the client application is allowed to request. This parameter will be
  *   one of the following. Details are described in the description. - an empty set - a set with at
  *   least one element If this parameter contains scopes that the service does not support, those
  *   scopes are just ignored. Also, if this parameter is `null` or is not included in the request,
  *   it is equivalent to calling `/client/extension/requestable_scopes/delete` API.
  */
case class ClientExtensionRequestableScopesUpdateRequest(
    requestableScopes: Option[Seq[String]] = None
)

object ClientExtensionRequestableScopesUpdateRequest {

  given jsonCodec: JsonValueCodec[ClientExtensionRequestableScopesUpdateRequest] =
    JsonCodecMaker.make(codecMakerConfig)

  given encoderClientExtensionRequestableScopesUpdateRequest
      : Encoder[ClientExtensionRequestableScopesUpdateRequest] = Encoder.instance { t =>
    Json.fromFields {
      Seq(
        t.requestableScopes.map(v => "requestableScopes" -> v.asJson)
      ).flatten
    }
  }

  given decoderClientExtensionRequestableScopesUpdateRequest
      : Decoder[ClientExtensionRequestableScopesUpdateRequest] = Decoder.instance { c =>
    for {
      requestableScopes <- c.downField("requestableScopes").as[Option[Seq[String]]]
    } yield ClientExtensionRequestableScopesUpdateRequest(
      requestableScopes = requestableScopes
    )
  }

}
