/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * @param clientId
  *   Client ID.
  * @param token
  *   Client registration access token.
  * @param json
  *   Client metadata in JSON format that complies with [RFC
  *   7591](https://datatracker.ietf.org/doc/html/rfc7591) (OAuth 2.0 Dynamic Client Registration
  *   Protocol).
  */
case class ClientRegistrationUpdateRequest(
    clientId: String,
    token: String,
    json: String
)

object ClientRegistrationUpdateRequest {

  given jsonCodec: JsonValueCodec[ClientRegistrationUpdateRequest] =
    JsonCodecMaker.make(codecMakerConfig)

  given encoderClientRegistrationUpdateRequest: Encoder[ClientRegistrationUpdateRequest] = Encoder
    .instance { t =>
      Json.fromFields {
        Seq(
          Some("clientId" -> t.clientId.asJson),
          Some("token"    -> t.token.asJson),
          Some("json"     -> t.json.asJson)
        ).flatten
      }
    }

  given decoderClientRegistrationUpdateRequest: Decoder[ClientRegistrationUpdateRequest] = Decoder
    .instance { c =>
      for {
        clientId <- c.downField("clientId").as[String]
        token    <- c.downField("token").as[String]
        json     <- c.downField("json").as[String]
      } yield ClientRegistrationUpdateRequest(
        clientId = clientId,
        token = token,
        json = json
      )
    }

}
