/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum ClientRegistrationResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends ClientRegistrationResponseAction("INTERNAL_SERVER_ERROR")
  case BADREQUEST          extends ClientRegistrationResponseAction("BAD_REQUEST")
  case CREATED             extends ClientRegistrationResponseAction("CREATED")

}

object ClientRegistrationResponseAction {

  def withValueOpt(value: String): Option[ClientRegistrationResponseAction] =
    ClientRegistrationResponseAction.values.find(_.value == value)

  def withValue(value: String): ClientRegistrationResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"ClientRegistrationResponseAction enum case not found: $value")
    )

  given decoderClientRegistrationResponseAction: Decoder[ClientRegistrationResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderClientRegistrationResponseAction: Encoder[ClientRegistrationResponseAction] = Encoder
    .encodeString
    .contramap[ClientRegistrationResponseAction](_.value)

}
