/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum ClientRegistrationUpdateResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends ClientRegistrationUpdateResponseAction("INTERNAL_SERVER_ERROR")
  case BADREQUEST          extends ClientRegistrationUpdateResponseAction("BAD_REQUEST")
  case UPDATED             extends ClientRegistrationUpdateResponseAction("UPDATED")
  case UNAUTHORIZED        extends ClientRegistrationUpdateResponseAction("UNAUTHORIZED")

}

object ClientRegistrationUpdateResponseAction {

  def withValueOpt(value: String): Option[ClientRegistrationUpdateResponseAction] =
    ClientRegistrationUpdateResponseAction.values.find(_.value == value)

  def withValue(value: String): ClientRegistrationUpdateResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(
          s"ClientRegistrationUpdateResponseAction enum case not found: $value"
        )
    )

  given decoderClientRegistrationUpdateResponseAction
      : Decoder[ClientRegistrationUpdateResponseAction] = Decoder.decodeString.map(withValue)

  given encoderClientRegistrationUpdateResponseAction
      : Encoder[ClientRegistrationUpdateResponseAction] = Encoder
    .encodeString
    .contramap[ClientRegistrationUpdateResponseAction](_.value)

}
