/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * @param clientId
  *   Client ID.
  * @param token
  *   Client registration access token.
  */
case class ClientRegistrationGetRequest(
    clientId: String,
    token: String
)

object ClientRegistrationGetRequest {

  given jsonCodec: JsonValueCodec[ClientRegistrationGetRequest] =
    JsonCodecMaker.make(codecMakerConfig)

  given encoderClientRegistrationGetRequest: Encoder[ClientRegistrationGetRequest] = Encoder
    .instance { t =>
      Json.fromFields {
        Seq(
          Some("clientId" -> t.clientId.asJson),
          Some("token"    -> t.token.asJson)
        ).flatten
      }
    }

  given decoderClientRegistrationGetRequest: Decoder[ClientRegistrationGetRequest] = Decoder
    .instance { c =>
      for {
        clientId <- c.downField("clientId").as[String]
        token    <- c.downField("token").as[String]
      } yield ClientRegistrationGetRequest(
        clientId = clientId,
        token = token
      )
    }

}
