/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum DeviceVerificationResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends DeviceVerificationResponseAction("INTERNAL_SERVER_ERROR")
  case NOTEXIST            extends DeviceVerificationResponseAction("NOT_EXIST")
  case EXPIRED             extends DeviceVerificationResponseAction("EXPIRED")
  case VALID               extends DeviceVerificationResponseAction("VALID")

}

object DeviceVerificationResponseAction {

  def withValueOpt(value: String): Option[DeviceVerificationResponseAction] =
    DeviceVerificationResponseAction.values.find(_.value == value)

  def withValue(value: String): DeviceVerificationResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"DeviceVerificationResponseAction enum case not found: $value")
    )

  given decoderDeviceVerificationResponseAction: Decoder[DeviceVerificationResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderDeviceVerificationResponseAction: Encoder[DeviceVerificationResponseAction] = Encoder
    .encodeString
    .contramap[DeviceVerificationResponseAction](_.value)

}
