/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum FederationRegistrationResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case OK                  extends FederationRegistrationResponseAction("OK")
  case BADREQUEST          extends FederationRegistrationResponseAction("BAD_REQUEST")
  case NOTFOUND            extends FederationRegistrationResponseAction("NOT_FOUND")
  case INTERNALSERVERERROR extends FederationRegistrationResponseAction("INTERNAL_SERVER_ERROR")

}

object FederationRegistrationResponseAction {

  def withValueOpt(value: String): Option[FederationRegistrationResponseAction] =
    FederationRegistrationResponseAction.values.find(_.value == value)

  def withValue(value: String): FederationRegistrationResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(
          s"FederationRegistrationResponseAction enum case not found: $value"
        )
    )

  given decoderFederationRegistrationResponseAction: Decoder[FederationRegistrationResponseAction] =
    Decoder.decodeString.map(withValue)

  given encoderFederationRegistrationResponseAction: Encoder[FederationRegistrationResponseAction] =
    Encoder.encodeString.contramap[FederationRegistrationResponseAction](_.value)

}
