/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * Result of the API call
  */
enum HskCreateResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case SUCCESS        extends HskCreateResponseAction("SUCCESS")
  case INVALIDREQUEST extends HskCreateResponseAction("INVALID_REQUEST")
  case NOTFOUND       extends HskCreateResponseAction("NOT_FOUND")
  case SERVERERROR    extends HskCreateResponseAction("SERVER_ERROR")

}

object HskCreateResponseAction {

  def withValueOpt(value: String): Option[HskCreateResponseAction] = HskCreateResponseAction
    .values
    .find(_.value == value)

  def withValue(value: String): HskCreateResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"HskCreateResponseAction enum case not found: $value")
    )

  given decoderHskCreateResponseAction: Decoder[HskCreateResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderHskCreateResponseAction: Encoder[HskCreateResponseAction] = Encoder
    .encodeString
    .contramap[HskCreateResponseAction](_.value)

}
