/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import scala.collection.immutable.Seq

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * @param resultCode
  *   The code which represents the result of the API call.
  * @param resultMessage
  *   A short message which explains the result of the API call.
  * @param action
  * @param hsks
  *   List of HSK
  */
case class HskGetListResponse(
    resultCode: Option[String] = None,
    resultMessage: Option[String] = None,
    action: Option[HskGetListResponseAction] = None,
    hsks: Option[Seq[Hsk]] = None
)

object HskGetListResponse {

  given jsonCodec: JsonValueCodec[HskGetListResponse] = JsonCodecMaker.make(codecMakerConfig)

  given encoderHskGetListResponse: Encoder[HskGetListResponse] = Encoder.instance { t =>
    Json.fromFields {
      Seq(
        t.resultCode.map(v => "resultCode" -> v.asJson),
        t.resultMessage.map(v => "resultMessage" -> v.asJson),
        t.action.map(v => "action" -> v.asJson),
        t.hsks.map(v => "hsks" -> v.asJson)
      ).flatten
    }
  }

  given decoderHskGetListResponse: Decoder[HskGetListResponse] = Decoder.instance { c =>
    for {
      resultCode    <- c.downField("resultCode").as[Option[String]]
      resultMessage <- c.downField("resultMessage").as[Option[String]]
      action        <- mapEmptyStringToNull(c.downField("action")).as[Option[HskGetListResponseAction]]
      hsks          <- c.downField("hsks").as[Option[Seq[Hsk]]]
    } yield HskGetListResponse(
      resultCode = resultCode,
      resultMessage = resultMessage,
      action = action,
      hsks = hsks
    )
  }

}
