/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * Result of the API call
  */
enum HskGetListResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case SUCCESS        extends HskGetListResponseAction("SUCCESS")
  case INVALIDREQUEST extends HskGetListResponseAction("INVALID_REQUEST")
  case SERVERERROR    extends HskGetListResponseAction("SERVER_ERROR")

}

object HskGetListResponseAction {

  def withValueOpt(value: String): Option[HskGetListResponseAction] = HskGetListResponseAction
    .values
    .find(_.value == value)

  def withValue(value: String): HskGetListResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"HskGetListResponseAction enum case not found: $value")
    )

  given decoderHskGetListResponseAction: Decoder[HskGetListResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderHskGetListResponseAction: Encoder[HskGetListResponseAction] = Encoder
    .encodeString
    .contramap[HskGetListResponseAction](_.value)

}
