/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the implementation of the token endpoint should take.
  */
enum IdtokenReissueResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case OK                  extends IdtokenReissueResponseAction("OK")
  case INTERNALSERVERERROR extends IdtokenReissueResponseAction("INTERNAL_SERVER_ERROR")
  case CALLERERROR         extends IdtokenReissueResponseAction("CALLER_ERROR")

}

object IdtokenReissueResponseAction {

  def withValueOpt(value: String): Option[IdtokenReissueResponseAction] =
    IdtokenReissueResponseAction.values.find(_.value == value)

  def withValue(value: String): IdtokenReissueResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"IdtokenReissueResponseAction enum case not found: $value")
    )

  given decoderIdtokenReissueResponseAction: Decoder[IdtokenReissueResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderIdtokenReissueResponseAction: Encoder[IdtokenReissueResponseAction] = Encoder
    .encodeString
    .contramap[IdtokenReissueResponseAction](_.value)

}
