/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * @param resultCode
  *   The code which represents the result of the API call.
  * @param resultMessage
  *   A short message which explains the result of the API call.
  * @param action
  * @param responseContent
  *   The response content that can be used as the message body of the token response that should be
  *   returned from the token endpoint.
  * @param idToken
  *   The reissued ID token
  */
case class IdtokenReissueResponse(
    resultCode: Option[String] = None,
    resultMessage: Option[String] = None,
    action: Option[IdtokenReissueResponseAction] = None,
    responseContent: Option[String] = None,
    idToken: Option[String] = None
)

object IdtokenReissueResponse {

  given jsonCodec: JsonValueCodec[IdtokenReissueResponse] = JsonCodecMaker.make(codecMakerConfig)

  given encoderIdtokenReissueResponse: Encoder[IdtokenReissueResponse] = Encoder.instance { t =>
    Json.fromFields {
      Seq(
        t.resultCode.map(v => "resultCode" -> v.asJson),
        t.resultMessage.map(v => "resultMessage" -> v.asJson),
        t.action.map(v => "action" -> v.asJson),
        t.responseContent.map(v => "responseContent" -> v.asJson),
        t.idToken.map(v => "idToken" -> v.asJson)
      ).flatten
    }
  }

  given decoderIdtokenReissueResponse: Decoder[IdtokenReissueResponse] = Decoder.instance { c =>
    for {
      resultCode      <- c.downField("resultCode").as[Option[String]]
      resultMessage   <- c.downField("resultMessage").as[Option[String]]
      action          <- mapEmptyStringToNull(c.downField("action")).as[Option[IdtokenReissueResponseAction]]
      responseContent <- c.downField("responseContent").as[Option[String]]
      idToken         <- c.downField("idToken").as[Option[String]]
    } yield IdtokenReissueResponse(
      resultCode = resultCode,
      resultMessage = resultMessage,
      action = action,
      responseContent = responseContent,
      idToken = idToken
    )
  }

}
