/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * @param key
  *   The key part.
  * @param value
  *   The value part.
  */
case class Pair(
    key: Option[String] = None,
    value: Option[String] = None
)

object Pair {

  given jsonCodec: JsonValueCodec[Pair] = JsonCodecMaker.make(codecMakerConfig)

  given encoderPair: Encoder[Pair] = Encoder.instance { t =>
    Json.fromFields {
      Seq(
        t.key.map(v => "key" -> v.asJson),
        t.value.map(v => "value" -> v.asJson)
      ).flatten
    }
  }

  given decoderPair: Decoder[Pair] = Decoder.instance { c =>
    for {
      key   <- c.downField("key").as[Option[String]]
      value <- c.downField("value").as[Option[String]]
    } yield Pair(
      key = key,
      value = value
    )
  }

}
