/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum RevocationResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends RevocationResponseAction("INTERNAL_SERVER_ERROR")
  case INVALIDCLIENT       extends RevocationResponseAction("INVALID_CLIENT")
  case BADREQUEST          extends RevocationResponseAction("BAD_REQUEST")
  case OK                  extends RevocationResponseAction("OK")

}

object RevocationResponseAction {

  def withValueOpt(value: String): Option[RevocationResponseAction] = RevocationResponseAction
    .values
    .find(_.value == value)

  def withValue(value: String): RevocationResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"RevocationResponseAction enum case not found: $value")
    )

  given decoderRevocationResponseAction: Decoder[RevocationResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderRevocationResponseAction: Encoder[RevocationResponseAction] = Encoder
    .encodeString
    .contramap[RevocationResponseAction](_.value)

}
