/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum StandardIntrospectionResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends StandardIntrospectionResponseAction("INTERNAL_SERVER_ERROR")
  case BADREQUEST          extends StandardIntrospectionResponseAction("BAD_REQUEST")
  case OK                  extends StandardIntrospectionResponseAction("OK")

}

object StandardIntrospectionResponseAction {

  def withValueOpt(value: String): Option[StandardIntrospectionResponseAction] =
    StandardIntrospectionResponseAction.values.find(_.value == value)

  def withValue(value: String): StandardIntrospectionResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(
          s"StandardIntrospectionResponseAction enum case not found: $value"
        )
    )

  given decoderStandardIntrospectionResponseAction: Decoder[StandardIntrospectionResponseAction] =
    Decoder.decodeString.map(withValue)

  given encoderStandardIntrospectionResponseAction: Encoder[StandardIntrospectionResponseAction] =
    Encoder.encodeString.contramap[StandardIntrospectionResponseAction](_.value)

}
