/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * @param resultCode
  *   The code which represents the result of the API call.
  * @param resultMessage
  *   A short message which explains the result of the API call.
  * @param action
  * @param responseContent
  *   The content that the authorization server implementation is to return to the client
  *   application.
  */
case class StandardIntrospectionResponse(
    resultCode: Option[String] = None,
    resultMessage: Option[String] = None,
    action: Option[StandardIntrospectionResponseAction] = None,
    responseContent: Option[String] = None
)

object StandardIntrospectionResponse {

  given jsonCodec: JsonValueCodec[StandardIntrospectionResponse] =
    JsonCodecMaker.make(codecMakerConfig)

  given encoderStandardIntrospectionResponse: Encoder[StandardIntrospectionResponse] = Encoder
    .instance { t =>
      Json.fromFields {
        Seq(
          t.resultCode.map(v => "resultCode" -> v.asJson),
          t.resultMessage.map(v => "resultMessage" -> v.asJson),
          t.action.map(v => "action" -> v.asJson),
          t.responseContent.map(v => "responseContent" -> v.asJson)
        ).flatten
      }
    }

  given decoderStandardIntrospectionResponse: Decoder[StandardIntrospectionResponse] = Decoder
    .instance { c =>
      for {
        resultCode    <- c.downField("resultCode").as[Option[String]]
        resultMessage <- c.downField("resultMessage").as[Option[String]]
        action <- mapEmptyStringToNull(c.downField("action")).as[Option[
                    StandardIntrospectionResponseAction
                  ]]
        responseContent <- c.downField("responseContent").as[Option[String]]
      } yield StandardIntrospectionResponse(
        resultCode = resultCode,
        resultMessage = resultMessage,
        action = action,
        responseContent = responseContent
      )
    }

}
