/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum TokenFailResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends TokenFailResponseAction("INTERNAL_SERVER_ERROR")
  case BADREQUEST          extends TokenFailResponseAction("BAD_REQUEST")

}

object TokenFailResponseAction {

  def withValueOpt(value: String): Option[TokenFailResponseAction] = TokenFailResponseAction
    .values
    .find(_.value == value)

  def withValue(value: String): TokenFailResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"TokenFailResponseAction enum case not found: $value")
    )

  given decoderTokenFailResponseAction: Decoder[TokenFailResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderTokenFailResponseAction: Encoder[TokenFailResponseAction] = Encoder
    .encodeString
    .contramap[TokenFailResponseAction](_.value)

}
