/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum TokenUpdateResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends TokenUpdateResponseAction("INTERNAL_SERVER_ERROR")
  case BADREQUEST          extends TokenUpdateResponseAction("BAD_REQUEST")
  case FORBIDDEN           extends TokenUpdateResponseAction("FORBIDDEN")
  case NOTFOUND            extends TokenUpdateResponseAction("NOT_FOUND")
  case OK                  extends TokenUpdateResponseAction("OK")

}

object TokenUpdateResponseAction {

  def withValueOpt(value: String): Option[TokenUpdateResponseAction] = TokenUpdateResponseAction
    .values
    .find(_.value == value)

  def withValue(value: String): TokenUpdateResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"TokenUpdateResponseAction enum case not found: $value")
    )

  given decoderTokenUpdateResponseAction: Decoder[TokenUpdateResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderTokenUpdateResponseAction: Encoder[TokenUpdateResponseAction] = Encoder
    .encodeString
    .contramap[TokenUpdateResponseAction](_.value)

}
