/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * @param resultCode
  *   The code which represents the result of the API call.
  * @param resultMessage
  *   A short message which explains the result of the API call.
  * @param count
  *   The number of tokens revoked
  */
case class TokenRevokeResponse(
    resultCode: Option[String] = None,
    resultMessage: Option[String] = None,
    count: Option[Int] = None
)

object TokenRevokeResponse {

  given jsonCodec: JsonValueCodec[TokenRevokeResponse] = JsonCodecMaker.make(codecMakerConfig)

  given encoderTokenRevokeResponse: Encoder[TokenRevokeResponse] = Encoder.instance { t =>
    Json.fromFields {
      Seq(
        t.resultCode.map(v => "resultCode" -> v.asJson),
        t.resultMessage.map(v => "resultMessage" -> v.asJson),
        t.count.map(v => "count" -> v.asJson)
      ).flatten
    }
  }

  given decoderTokenRevokeResponse: Decoder[TokenRevokeResponse] = Decoder.instance { c =>
    for {
      resultCode    <- c.downField("resultCode").as[Option[String]]
      resultMessage <- c.downField("resultMessage").as[Option[String]]
      count         <- c.downField("count").as[Option[Int]]
    } yield TokenRevokeResponse(
      resultCode = resultCode,
      resultMessage = resultMessage,
      count = count
    )
  }

}
