/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The next action that the authorization server implementation should take.
  */
enum TokenIssueResponseAction(val value: String) derives ConfiguredJsonValueCodec {

  case INTERNALSERVERERROR extends TokenIssueResponseAction("INTERNAL_SERVER_ERROR")
  case OK                  extends TokenIssueResponseAction("OK")

}

object TokenIssueResponseAction {

  def withValueOpt(value: String): Option[TokenIssueResponseAction] = TokenIssueResponseAction
    .values
    .find(_.value == value)

  def withValue(value: String): TokenIssueResponseAction =
    withValueOpt(value).getOrElse(
      throw java
        .lang
        .IllegalArgumentException(s"TokenIssueResponseAction enum case not found: $value")
    )

  given decoderTokenIssueResponseAction: Decoder[TokenIssueResponseAction] = Decoder
    .decodeString
    .map(withValue)

  given encoderTokenIssueResponseAction: Encoder[TokenIssueResponseAction] = Encoder
    .encodeString
    .contramap[TokenIssueResponseAction](_.value)

}
