/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12 Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package models

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.ConfiguredJsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker
import io.circe.{Decoder, Encoder, Json}
import io.circe.syntax.*

/**
  * The character set for end-user verification codes (`user_code`) for Device Flow.
  */
enum UserCodeCharset(val value: String) derives ConfiguredJsonValueCodec {

  case BASE20  extends UserCodeCharset("BASE20")
  case NUMERIC extends UserCodeCharset("NUMERIC")

}

object UserCodeCharset {

  def withValueOpt(value: String): Option[UserCodeCharset] = UserCodeCharset
    .values
    .find(_.value == value)

  def withValue(value: String): UserCodeCharset =
    withValueOpt(value).getOrElse(
      throw java.lang.IllegalArgumentException(s"UserCodeCharset enum case not found: $value")
    )

  given decoderUserCodeCharset: Decoder[UserCodeCharset] = Decoder.decodeString.map(withValue)

  given encoderUserCodeCharset: Encoder[UserCodeCharset] = Encoder
    .encodeString
    .contramap[UserCodeCharset](_.value)

}
