/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package apis

import sttp.client4._
import sttp.client4.Backend
import sttp.model.Method

trait MiscEndpoints[F[*]] {

  /**
    * Echo test endpoint. Will return all path parameters in the request
    *
    * Expected answers: code 200 : (Successfully deleted )
    *
    * Available security schemes: ServiceCredentials (http)
    */
  def miscEcho(
  ): F[Unit]

}
