/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package apis

import cats.effect.Concurrent

import authlete.models.HskCreateRequest
import authlete.models.HskCreateResponse
import authlete.models.HskDeleteResponse
import authlete.models.HskGetListResponse
import authlete.models.HskGetResponse
import authlete.models.Result
import config.AuthleteConfig
import org.typelevel.log4cats.Logger
import sttp.client4.*
import sttp.client4._
import sttp.client4.jsoniter.*
import sttp.client4.Backend
import sttp.model.MediaType
import sttp.model.Method
import sttp.model.StatusCode
import sttp.model.Uri
//import authlete.models.JsoniterSyntaticSugar.*
// import authlete.models.

trait HskOperationsEndpoints[F[*]] {

  /**
    * Expected answers: code 200 : HskCreateResponse () code 400 : Result () code 401 : Result ()
    * code 403 : Result () code 500 : Result ()
    *
    * Available security schemes: ServiceOwnerCredentials (http)
    *
    * @param hskCreateRequest
    */
  def hskCreate(
      hskCreateRequest: HskCreateRequest
  ): F[HskCreateResponse]

  /**
    * Expected answers: code 204 : HskDeleteResponse code 400 : Result () code 401 : Result () code
    * 403 : Result () code 500 : Result ()
    *
    * Available security schemes: ServiceOwnerCredentials (http)
    *
    * @param handle
    */
  def hskDelete(
      handle: String
  ): F[HskDeleteResponse]

  /**
    * Expected answers: code 200 : HskGetResponse () code 400 : Result () code 401 : Result () code
    * 403 : Result () code 500 : Result ()
    *
    * Available security schemes: ServiceOwnerCredentials (http)
    *
    * @param handle
    */
  def hskGet(
      handle: String
  ): F[HskGetResponse]

  /**
    * Expected answers: code 200 : HskGetListResponse code 400 : Result () code 401 : Result () code
    * 403 : Result () code 500 : Result ()
    *
    * Available security schemes: ServiceOwnerCredentials (http)
    */
  def hskGetList(
  ): F[HskGetListResponse]

}

class HskOperationsEndpointsImpl[F[*]: Concurrent](
    backend: Backend[F],
    config: AuthleteConfig,
    logger: Logger[F]
) extends HskOperationsEndpoints[F] {

  override def hskCreate(hskCreateRequest: HskCreateRequest): F[HskCreateResponse] = ???

  override def hskDelete(handle: String): F[HskDeleteResponse] = ???

  override def hskGet(handle: String): F[HskGetResponse] = ???

  override def hskGetList(): F[HskGetListResponse] = ???

}
