/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package apis

import cats.effect.Concurrent

import authlete.models.JoseVerifyRequest
import authlete.models.JoseVerifyResponse
import authlete.models.Result
import config.AuthleteConfig
import org.typelevel.log4cats.Logger
import sttp.client4.*
import sttp.client4._
import sttp.client4.jsoniter.*
import sttp.client4.Backend
import sttp.model.MediaType
import sttp.model.Method
import sttp.model.StatusCode
import sttp.model.Uri
//import authlete.models.JsoniterSyntaticSugar.*
// import authlete.models.

trait JoseObjectEndpoints[F[*]] {

  /**
    * This API verifies a JOSE object.
    *
    * Expected answers: code 200 : JoseVerifyResponse () code 400 : Result () code 401 : Result ()
    * code 403 : Result () code 500 : Result ()
    *
    * Available security schemes: ServiceOwnerCredentials (http)
    *
    * @param joseVerifyRequest
    */
  def joseVerify(
      joseVerifyRequest: Option[JoseVerifyRequest] = None
  ): F[JoseVerifyResponse]

}

class JoseObjectEndpointsImpl[F[*]: Concurrent](
    backend: Backend[F],
    config: AuthleteConfig,
    logger: Logger[F]
) extends JoseObjectEndpoints[F] {

  override def joseVerify(joseVerifyRequest: Option[JoseVerifyRequest]): F[JoseVerifyResponse] = ???
}
