/**
  * Authlete API Authlete API Document.
  *
  * The version of the OpenAPI document: 2.3.12
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package authlete
package apis

import cats.effect.Concurrent

import authlete.models.Result
import authlete.models.ServiceJwksGetResponse
import config.AuthleteConfig
import org.typelevel.log4cats.Logger
import sttp.client4.*
import sttp.client4._
import sttp.client4.jsoniter.*
import sttp.client4.Backend
import sttp.model.MediaType
import sttp.model.Method
import sttp.model.StatusCode
import sttp.model.Uri
//import authlete.models.JsoniterSyntaticSugar.*
// import authlete.models.

trait JWKSetEndpoints[F[*]] {

  /**
    * This API gathers JWK Set information for a service so that its client applications can verify
    * signatures by the service and encrypt their requests to the service. <br> <details>
    * <summary>Description</summary> This API is supposed to be called from within the
    * implementation of the jwk set endpoint of the service where the service that supports OpenID
    * Connect must expose its JWK Set information so that client applications can verify signatures
    * by the service and encrypt their requests to the service. The URI of the endpoint can be found
    * as the value of `jwks_uri` in [OpenID Provider
    * Metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) if the
    * service supports [OpenID Connect Discovery
    * 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html). </details>
    *
    * Expected answers: code 200 : ServiceJwksGetResponse () code 204 : (No JWK Set nor JwkUri was
    * found.) code 400 : Result () code 401 : Result () code 403 : Result () code 500 : Result ()
    *
    * Available security schemes: ServiceCredentials (http)
    *
    * @param includePrivateKeys
    *   The boolean value that indicates whether the response should include the private keys
    *   associated with the service or not. If `true`, the private keys are included in the
    *   response. The default value is `false`.
    * @param pretty
    *   This boolean value indicates whether the JSON in the response should be formatted or not. If
    *   `true`, the JSON in the response is pretty-formatted. The default value is `false`.
    */
  def serviceJwksGet(
      includePrivateKeys: Option[Boolean] = None,
      pretty: Option[Boolean] = None
  ): F[ServiceJwksGetResponse]

}

class JWKSetEndpointsImpl[F[*]: Concurrent](
    backend: Backend[F],
    config: AuthleteConfig,
    logger: Logger[F]
) extends JWKSetEndpoints[F] {

  override def serviceJwksGet(
      includePrivateKeys: Option[Boolean],
      pretty: Option[Boolean]
  ): F[ServiceJwksGetResponse] = ???

}
